apiVersion: v1
kind: ServiceAccount
metadata:
  name: nightwatch
  namespace: nightwatch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nightwatch
  namespace: nightwatch
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources:
  - jobs
  - pods
  - cronjobs
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nightwatch
  namespace: nightwatch
subjects:
- kind: ServiceAccount
  name: nightwatch
  namespace: nightwatch
roleRef:
  kind: ClusterRole
  name: nightwatch
  apiGroup: rbac.authorization.k8s.io
